import { Product } from "@/types";

export const PRODUCTS_CONFIG: Record<string, {
  heroImageAlt: string;
  shortPromise: string;
  heroAngle: string;
  problemStatement: string;
  /** Optional image used only in the product page hero (not catalog/cards) */
  heroSectionImage?: string;
  heroSectionImageAlt?: string;
  heroSectionAspect?: string;
  /** Optional image used only in the pain/problem section on the product page */
  painSectionImage?: string;
  painSectionImageAlt?: string;
  painSectionAspect?: string;
  /** Optional image used only in the solution section on the product page */
  solutionSectionImage?: string;
  solutionSectionImageAlt?: string;
  solutionSectionAspect?: string;
  /** Optional image used only in the lifestyle/benefits section on the product page */
  lifestyleSectionImage?: string;
  lifestyleSectionImageAlt?: string;
  lifestyleSectionAspect?: string;
  /** Optional image used only in the before/after "after" card on the product page */
  afterSectionImage?: string;
  afterSectionImageAlt?: string;
  afterSectionAspect?: string;
  /** Optional image used only in the before/after "before" card on the product page */
  beforeSectionImage?: string;
  beforeSectionImageAlt?: string;
  beforeSectionAspect?: string;
  benefits: string[];
  beforeLabel: string;
  afterLabel: string;
  howToUse: string[];
  crossSellSlugs: string[];
  reviews: Array<{ name: string; city: string; rating: number; text: string; photo?: string; photoAlt?: string; photoAspect?: string }>;
  faqs: Array<{ question: string; answer: string }>;
  seoTitle: string;
  seoDescription: string;
}> = {
  "powerful-cordless-vacuum": {
    heroImageAlt: "المكنسة اللاسلكية القوية أثناء تنظيف مقعد السيارة",
    shortPromise: "تنظيف سريع وفعّال يمنح منزلك وسيارتك مظهرًا أنظف خلال دقائق",
    heroAngle: "أداة تنظيف يومية سريعة للفوضى الصغيرة في المنزل والسيارة",
    problemStatement: "الغبار والفتات في ركنة الكنب، مقاعد السيارة، وسطح المطبخ لا يستحق إخراج المكنسة الكبيرة. المكنسة اللاسلكية القوية من متقن هي الحل اليومي العملي.",
    benefits: [
      "تنظيف خفيف وسريع في ثوانٍ",
      "مناسبة للمنزل والسيارة",
      "سهلة الحمل والتخزين",
      "فلتر قابل للتنظيف",
      "شحن مريح ومدة تشغيل مناسبة",
    ],
    beforeLabel: "قبل: فتات وغبار في المقاعد",
    afterLabel: "بعد متقن: سيارة ومنزل أنظف",
    howToUse: [
      "اشحن المكنسة قبل الاستخدام الأول",
      "اختر الملحق المناسب للسطح",
      "أدر المكنسة على المنطقة المراد تنظيفها",
      "فرّغ الحاوية ونظف الفلتر بانتظام",
    ],
    crossSellSlugs: ["pull-out-cabinet-drawer", "magic-under-sink-organizer"],
    reviews: [
      { name: "سارة أحمد", city: "الرياض", rating: 5, text: "استخدمتها للسيارة والكنب وما شاء الله فرق واضح. سهلة الاستخدام وسريعة الشحن." },
      { name: "منال الشهري", city: "جدة", rating: 5, text: "قطعتين أخذت واحدة للبيت وواحدة للسيارة. أفضل قرار. مريحة جدًا للفتات اليومي." },
      { name: "نوف العتيبي", city: "الدمام", rating: 4, text: "خفيفة الوزن وفعّالة. أنصح فيها لكل بيت فيه أطفال." },
      { name: "عبير الراشد", city: "الطائف", rating: 5, text: "من أفضل المنتجات اللي طلبتها أونلاين. الشفط قوي والبطارية تمشي وقت طويل." },
      { name: "لمياء السبيعي", city: "بريدة", rating: 5, text: "استخدمتها لتنظيف كراسي الأطفال في السيارة. ممتازة ونتيجة فورية." },
      { name: "هند القرني", city: "أبها", rating: 5, text: "شكل المكنسة أنيق وخفيفة. أحسن شيء إنها لاسلكية ما تحتاج أسلاك." },
    ],
    faqs: [
      { question: "هل تناسب السيارة والمنزل؟", answer: "نعم، تأتي بملحقات مناسبة للمقاعد، الأركان، وأسطح المطبخ والسيارة." },
      { question: "هل هي بديلة للمكنسة الكبيرة؟", answer: "هي مكملة للمكنسة الكبيرة، وليست بديلة. مثالية للتنظيف اليومي الخفيف والسريع." },
      { question: "كيف يتم تنظيف الفلتر؟", answer: "يُفتح الفلتر بسهولة ويُنظف بالماء ويُجفف تمامًا قبل إعادة التركيب." },
      { question: "كم مدة التوصيل؟", answer: "عادة 2-5 أيام عمل داخل المدن الرئيسية في المملكة." },
      { question: "هل الدفع عند الاستلام متاح؟", answer: "نعم، الدفع عند الاستلام هو طريقة الدفع الوحيدة حاليًا. ادفع عند استلام الطلب بكل راحة." },
    ],
    seoTitle: "المكنسة اللاسلكية القوية | متقن",
    seoDescription: "تنظيف سريع وفعّال يمنح منزلك وسيارتك مظهرًا أنظف خلال دقائق. اطلب الآن من متقن مع الدفع عند الاستلام والتوصيل داخل السعودية.",
  },
  "smart-stackable-cabinet": {
    heroImageAlt: "الخزانة التراكمية الذكية بجانب المغسلة — تخزين منظم للمنزل",
    heroSectionImage: "/images/products/smart-stackable-cabinet-couple-hero.png?v=3",
    heroSectionImageAlt: "رجل وامرأة مع الخزانة التراكمية الذكية — حل تنظيم يناسب كل البيت",
    heroSectionAspect: "884/1015",
    shortPromise: "نظام تخزين فاخر يمنحك مساحة إضافية وترتيبًا أنيقًا خلال دقائق",
    heroAngle: "حوّل الزوايا المهملة إلى مساحة تخزين أنيقة ومنظمة",
    problemStatement: "المساحة ليست المشكلة، بل طريقة استخدامها. الخزانة التراكمية تستغل المساحة العمودية وتحوّل أي ركن إلى مخزن منظم وجميل.",
    painSectionImage: "/images/products/smart-stackable-cabinet-chaos.png",
    painSectionImageAlt: "زوجان متعبان من فوضى البيت — المشكلة التي تحلها الخزانة التراكمية",
    solutionSectionImage: "/images/products/smart-stackable-cabinet-assembly.png",
    solutionSectionImageAlt: "رجل يركّب الخزانة التراكمية الذكية بسهولة في البيت",
    lifestyleSectionImage: "/images/products/smart-stackable-cabinet-woman.png",
    lifestyleSectionImageAlt: "امرأة بجانب الخزانة التراكمية الذكية — تناسب كل غرفة في البيت",
    afterSectionImage: "/images/products/smart-stackable-cabinet-laundry-sink.png",
    afterSectionImageAlt: "الخزانة التراكمية الذكية بجانب المغسلة — تخزين أنيق ومرتب",
    beforeSectionImage: "/images/products/smart-stackable-cabinet-laundry-mess.png",
    beforeSectionImageAlt: "زاوية مغسلة مزدحمة وغير منظمة — قبل استخدام الخزانة التراكمية",
    benefits: [
      "تركيب سريع بدون أدوات",
      "تراكمية وقابلة للتوسع",
      "مواد متينة تتحمل الاستخدام اليومي",
      "تناسب غرف النوم، الحمام، والمطبخ",
      "تصميم أنيق يليق بالمنازل العصرية",
    ],
    beforeLabel: "قبل: زاوية مزدحمة وغير منظمة",
    afterLabel: "بعد متقن: تخزين أنيق ومرتب",
    howToUse: [
      "اختر الموقع المناسب لوضع الخزانة",
      "ابدأ بالقطعة السفلية وثبّتها",
      "أضف القطع العلوية بسهولة",
      "رتب أغراضك وامتع بالنظام الجديد",
    ],
    crossSellSlugs: ["pull-out-cabinet-drawer", "magic-under-sink-organizer"],
    reviews: [
      {
        name: "هنوف القحطاني",
        city: "الرياض",
        rating: 5,
        text: "حطيتها في زاوية غرفة النوم وما شاء الله غيرت شكل الأوضة بالكامل. تركيب سهل وتصميم راقي.",
        photo: "/images/reviews/smart-stackable-cabinet/review-living-room.png",
        photoAlt: "صورة من هنوف — الخزانة في غرفة المعيشة بعد التركيب",
        photoAspect: "576/983",
      },
      {
        name: "ريم الزهراني",
        city: "مكة",
        rating: 5,
        text: "أخذت قطعتين للحمام وغرفة الملابس. تنظيم مثالي وبسعر ممتاز.",
        photo: "/images/reviews/smart-stackable-cabinet/review-hallway.png",
        photoAlt: "صورة من ريم — الخزانة في الممر بعد الاستلام",
        photoAspect: "401/663",
      },
      { name: "دلال الحربي", city: "الدمام", rating: 5, text: "شكلها فخم ومرتبة. استغليت مساحة ما كنت أستخدمها أبداً. أنصح فيها بشدة." },
      {
        name: "مها العمري",
        city: "الطائف",
        rating: 5,
        text: "حطيت واحدة في المطبخ والثانية في الحمام. ترتيب ممتاز وتوفير مساحة.",
        photo: "/images/reviews/smart-stackable-cabinet/review-kitchen-use.png",
        photoAlt: "صورة من مها — استخدام الخزانة في المطبخ",
        photoAspect: "406/664",
      },
      {
        name: "سلمى الخالدي",
        city: "تبوك",
        rating: 4,
        text: "جودة ممتازة والتركيب سهل بدون أدوات. تصميم عملي يناسب أي مكان.",
        photo: "/images/reviews/smart-stackable-cabinet/review-unboxing.png",
        photoAlt: "صورة من سلمى — الخزانة بعد التركيب في البيت",
        photoAspect: "400/672",
      },
      { name: "عهود البلوي", city: "المدينة", rating: 5, text: "أفضل حل للتخزين جربته. صار البيت أنظم وأريح بكثير." },
    ],
    faqs: [
      { question: "هل يمكن تركيبها فوق بعضها؟", answer: "نعم، صُممت خصيصًا لتثبت فوق بعضها بأمان." },
      { question: "أين يمكن استخدامها؟", answer: "في أي مكان: غرف النوم، الحمام، المطبخ، مناطق التخزين، أو الغرف الجانبية." },
      { question: "هل تحتاج أدوات تركيب؟", answer: "لا، التركيب بسيط جدًا ولا يحتاج أي أدوات." },
      { question: "هل يمكن طلب قطعتين؟", answer: "نعم، وباقة القطعتين توفر لك 99 ريالًا وتتيح تنظيم أكثر من مساحة." },
    ],
    seoTitle: "الخزانة التراكمية الذكية | متقن",
    seoDescription: "نظام تخزين فاخر يمنحك مساحة إضافية وترتيبًا أنيقًا. اطلب الآن مع الدفع عند الاستلام والتوصيل داخل السعودية.",
  },
  "pull-out-cabinet-drawer": {
    heroImageAlt: "درج الخزانة المنزلق — تنظيم أدوات المطبخ بسهولة",
    heroSectionImage: "/images/products/pull-out-cabinet-drawer-hero.png",
    heroSectionImageAlt: "درج الخزانة المنزلق مفتوح — بهارات وأواني منظمة بسهولة",
    heroSectionAspect: "930/1024",
    shortPromise: "حل ذكي لتنظيم الخزائن المزدحمة والوصول لأغراضك بسهولة",
    heroAngle: "اجعل المساحة المخفية خلف الخزانة سهلة الوصول في ثانية واحدة",
    problemStatement: "الأغراض في آخر الخزانة تُنسى ولا تُستخدم. الدرج المنزلق يجلب كل شيء إلى متناول يدك في لحظة.",
    painSectionImage: "/images/products/pull-out-cabinet-drawer-chaos.png",
    painSectionImageAlt: "امرأة أمام خزانة مطبخ مزدحمة — صعوبة الوصول للأواني في الخلف",
    painSectionAspect: "1024/681",
    solutionSectionImage: "/images/products/pull-out-cabinet-drawer-solution.png",
    solutionSectionImageAlt: "امرأة تستخدم الدرج المنزلق — بهارات وأواني منظمة بسهولة",
    solutionSectionAspect: "1024/976",
    lifestyleSectionImage: "/images/products/pull-out-cabinet-drawer-lifestyle.png",
    lifestyleSectionImageAlt: "امرأة تطبخ وتستخدم الدرج المنزلق — تنظيم المطبخ بسهولة",
    lifestyleSectionAspect: "1024/681",
    benefits: [
      "وصول سهل لأعمق نقطة في الخزانة",
      "انزلاق سلس وصامت",
      "يتحمل أوزان البهارات وأدوات التنظيف",
      "سهل التركيب والإزالة",
      "متوفر بباقات تناسب المطبخ والحمام",
    ],
    beforeLabel: "قبل: أشياء مخبأة وصعبة الوصول",
    beforeSectionImage: "/images/products/pull-out-cabinet-drawer-before.png",
    beforeSectionImageAlt: "خزانة مطبخ مزدحمة — أواني ومرطبانات صعبة الوصول",
    beforeSectionAspect: "1024/771",
    afterLabel: "بعد متقن: كل شيء بمتناول يدك",
    afterSectionImage: "/images/products/pull-out-cabinet-drawer-after.png",
    afterSectionImageAlt: "امرأة تستخدم الدرج المنزلق — كل شيء بمتناول اليد",
    afterSectionAspect: "1024/768",
    howToUse: [
      "قِس عرض الخزانة قبل الطلب",
      "ضع الدرج على القاعدة المخصصة",
      "اسحب ببساطة للوصول لأغراضك",
    ],
    crossSellSlugs: ["magic-under-sink-organizer", "smart-stackable-cabinet"],
    reviews: [
      {
        name: "نورة العنزي",
        city: "الرياض",
        rating: 5,
        text: "أكثر شيء فرق معي أن الأشياء اللي كانت في آخر الخزانة صارت سهلة الوصول. ممتازة جدًا.",
        photo: "/images/reviews/pull-out-cabinet-drawer/review-pantry-extended.png",
        photoAlt: "صورة من نورة — الدرج المنزلق ممتد داخل الخزانة",
        photoAspect: "1024/768",
      },
      {
        name: "فوز الدوسري",
        city: "الخبر",
        rating: 5,
        text: "طلبت 4 قطع للمطبخ. الفرق كبير جدًا في الترتيب والوصول للبهارات والأواني.",
        photo: "/images/reviews/pull-out-cabinet-drawer/review-pantry-shelves.png",
        photoAlt: "صورة من فوز — درجين منزلقين منظّمين في المطبخ",
        photoAspect: "768/1024",
      },
      {
        name: "ابتسام الحربي",
        city: "الدمام",
        rating: 4,
        text: "تركيبها سهل جدًا والانزلاق سلس. راضية جدًا عن الشراء.",
        photo: "/images/reviews/pull-out-cabinet-drawer/review-wood-cabinet.png",
        photoAlt: "صورة من ابتسام — الدرج المنزلق بعد التركيب في الخزانة",
        photoAspect: "768/1024",
      },
      {
        name: "وجدان المالكي",
        city: "جدة",
        rating: 5,
        text: "كل الخزائن صارت منظمة. البهارات والأواني كلها بمتناول اليد بدون أي جهد.",
        photo: "/images/reviews/pull-out-cabinet-drawer/review-pantry-drawer.png",
        photoAlt: "صورة من وجدان — درج منزلق ممتلئ بمستلزمات المطبخ",
        photoAspect: "768/1024",
      },
      {
        name: "نجلاء الزهراني",
        city: "مكة",
        rating: 5,
        text: "أخذت 6 قطع للبيت كامل. صراحة أفضل شيء سويته للمطبخ من سنوات.",
        photo: "/images/reviews/pull-out-cabinet-drawer/review-kitchen-install.png",
        photoAlt: "صورة من نجلاء — درجين منزلقين في خزانة المطبخ",
        photoAspect: "768/1024",
      },
      {
        name: "رنا الشريف",
        city: "حائل",
        rating: 5,
        text: "حتى زوجي لاحظ الفرق في المطبخ. الانزلاق ناعم والجودة عالية.",
        photo: "/images/reviews/pull-out-cabinet-drawer/review-under-sink.png",
        photoAlt: "صورة من رنا — الدرج المنزلق تحت الخزانة منظّم",
        photoAspect: "768/1024",
      },
    ],
    faqs: [
      { question: "كيف أعرف أنها تناسب خزانتي؟", answer: "قس عرض الخزانة الداخلي. فريق التأكيد يساعدك للتأكد قبل الشحن." },
      { question: "هل تحتاج تركيب؟", answer: "لا، توضع مباشرة داخل الخزانة بدون أي تثبيت أو أدوات." },
      { question: "هل تتحمل أدوات المطبخ؟", answer: "نعم، مصممة لتتحمل البهارات وأدوات التنظيف والعلب." },
      { question: "ما الفرق بين الباقات؟", answer: "الباقة 2 للبداية، الباقة 4 للمطبخ كاملًا (الأكثر اختيارًا)، والباقة 6 لمن يريد تنظيم البيت بالكامل." },
      { question: "هل يمكن استخدامها تحت المغسلة؟", answer: "نعم، تعمل بشكل ممتاز تحت المغسلة مع مراعاة المواسير." },
    ],
    seoTitle: "درج الخزانة المنزلق | متقن",
    seoDescription: "حل ذكي لتنظيم الخزائن المزدحمة والوصول لأغراضك بسهولة. اطلب الآن من متقن مع الدفع عند الاستلام.",
  },
  "magic-under-sink-organizer": {
    heroImageAlt: "منظّم المغسلة السحري — تنظيم أنيق تحت المغسلة",
    heroSectionImage: "/images/products/magic-under-sink-organizer-hero.png?v=3",
    heroSectionImageAlt: "امرأة برداء بيج تستخدم منظّم المغسلة السحري تحت الحوض — تخزين ذكي ومرتب",
    heroSectionAspect: "819/1024",
    shortPromise: "تصميم عملي يساعدك على استغلال مساحة المغسلة بشكل أكثر ترتيبًا وراحة",
    heroAngle: "المساحة المخفية تحت المغسلة يمكن أن تكون أكثر مساحاتك ترتيبًا",
    problemStatement: "زجاجات التنظيف مكوّمة، والمواسير تحتل نصف المساحة. المنظّم السحري يحوّل هذه الفوضى إلى تخزين ذكي ومرتب.",
    benefits: [
      "يستغل المساحة العمودية تحت المغسلة",
      "يتجاوز المواسير بتصميم مرن",
      "يتحمل زجاجات ومنظفات المطبخ",
      "سهل التركيب والتخصيص",
      "مناسب للمطبخ والحمام",
    ],
    beforeLabel: "قبل: فوضى تحت المغسلة",
    afterLabel: "بعد متقن: ترتيب ذكي يسهّل يومك",
    howToUse: [
      "قس المساحة تحت مغسلتك",
      "ركّب الرفوف مع مراعاة موضع المواسير",
      "رتب زجاجاتك وأدوات التنظيف",
    ],
    crossSellSlugs: ["pull-out-cabinet-drawer", "pure-faucet-filter"],
    reviews: [
      { name: "هيا المطيري", city: "جدة", rating: 5, text: "كان تحت مغسلة المطبخ عندي فوضى كاملة، المنظّم غير كل شيء. تركيب بدون أدوات وممتاز جدًا." },
      { name: "خلود الشمري", city: "الرياض", rating: 5, text: "أخذته للمطبخ والحمام. أفضل منتج جربته للتنظيم." },
      { name: "بشاير العجمي", city: "الخبر", rating: 5, text: "المواسير ما أثرت أبداً. المنظم يلف حول المواسير بسهولة. تصميم ذكي فعلاً." },
      { name: "غادة النفيعي", city: "الدمام", rating: 5, text: "أخيراً تحت المغسلة صار مرتب ونظيف. كل شيء بمكانه." },
      { name: "حصة الرشيدي", city: "بريدة", rating: 4, text: "جودة ممتازة والتركيب ما أخذ أكثر من 5 دقائق. أنصح فيه." },
      { name: "فاطمة الجهني", city: "المدينة", rating: 5, text: "طلبت قطعتين للمطبخ والحمام. النتيجة فاقت توقعاتي بصراحة." },
    ],
    faqs: [
      { question: "هل يناسب وجود مواسير تحت المغسلة؟", answer: "نعم، صُمم ليعمل مع المواسير بتصميم مرن يتكيف مع المساحة." },
      { question: "هل يمكن استخدامه في الحمام؟", answer: "نعم، مثالي للحمام والمطبخ على حد سواء." },
      { question: "هل يتحمل علب التنظيف؟", answer: "نعم، مصنوع من مواد متينة تتحمل زجاجات التنظيف والعلب." },
      { question: "هل يحتاج تركيب؟", answer: "التركيب بسيط جدًا ولا يحتاج أدوات أو حفر." },
    ],
    seoTitle: "منظّم المغسلة السحري | متقن",
    seoDescription: "تصميم عملي يساعدك على استغلال مساحة المغسلة. اطلب الآن من متقن مع الدفع عند الاستلام.",
  },
  "pure-faucet-filter": {
    heroImageAlt: "فلتر الصنبور النقي مركب على صنبور المطبخ",
    shortPromise: "مياه أنقى وتجربة استخدام يومية أكثر راحة وأناقة للمطبخ العصري",
    heroAngle: "تجربة استخدام ماء الصنبور اليومية أكثر راحة وأناقة",
    problemStatement: "طعم ماء الصنبور ومظهره يؤثران على التجربة اليومية في المطبخ. الفلتر يساعد على تحسين تجربة استخدام الماء اليومية.",
    benefits: [
      "يساعد على تحسين تجربة استخدام ماء الصنبور",
      "تركيب سهل على معظم الصنابير",
      "تصميم أنيق يليق بمطبخ عصري",
      "يأتي بمحولات للصنابير المختلفة",
      "اقتصادي وعملي للاستخدام اليومي",
    ],
    beforeLabel: "قبل: صنبور عادي بدون فلتر",
    afterLabel: "بعد متقن: تجربة ماء أنيقة ومريحة",
    howToUse: [
      "اختر المحول المناسب لصنبورك من المجموعة المرفقة",
      "ثبّت الفلتر على الصنبور",
      "افتح الماء واستمتع بتجربة أفضل",
    ],
    crossSellSlugs: ["magic-under-sink-organizer", "smart-table-warmer"],
    reviews: [
      { name: "أسماء العمري", city: "الرياض", rating: 5, text: "تركيب سهل جدًا وفرق واضح في شكل المطبخ. سعيدة بالشراء." },
      { name: "لطيفة الغامدي", city: "مكة", rating: 4, text: "المنتج مرتب وأنيق. التركيب أخذ دقيقتين فقط. ممتاز للمطبخ." },
      { name: "شوق الحازمي", city: "جدة", rating: 5, text: "الفلتر حسّن تجربة المطبخ بشكل ملحوظ. شكله أنيق على الصنبور." },
      { name: "نوال السويلم", city: "الخرج", rating: 5, text: "سهل التركيب وعملي جداً. صار المطبخ يبان أحلى مع الفلتر." },
      { name: "عبير الخثلان", city: "الدمام", rating: 5, text: "أخذت قطعتين واحدة لي وواحدة هدية لأختي. كلنا راضيات." },
      { name: "مريم البقمي", city: "الطائف", rating: 4, text: "المحولات المرفقة ناسبت صنبوري تماماً. تركيب بدون أي مشاكل." },
    ],
    faqs: [
      { question: "هل يناسب كل الصنابير؟", answer: "يأتي بمجموعة من المحولات تناسب معظم أحجام الصنابير الشائعة. فريق التأكيد يساعد للتحقق قبل الشحن." },
      { question: "هل يأتي معه محولات؟", answer: "نعم، تأتي المجموعة بمحولات متعددة للصنابير المختلفة." },
      { question: "كيف يتم تركيبه؟", answer: "يُلوى على فوهة الصنبور بكل سهولة بدون أي أدوات." },
      { question: "هل الدفع عند الاستلام متاح؟", answer: "نعم، الدفع عند الاستلام متاح ومريح لجميع طلباتنا." },
    ],
    seoTitle: "فلتر الصنبور النقي | متقن",
    seoDescription: "مياه أنقى وتجربة استخدام يومية أكثر راحة وأناقة للمطبخ العصري. اطلب الآن مع الدفع عند الاستلام.",
  },
  "smart-table-warmer": {
    heroImageAlt: "سخّان المائدة الذكي على طاولة عائلية",
    heroSectionImage: "/images/products/smart-table-warmer-hero.png",
    heroSectionImageAlt: "عائلة سعودية حول مائدة مع سخّان المائدة الذكي — طعام دافئ طوال الجلسة",
    heroSectionAspect: "1024/918",
    shortPromise: "حل عملي فاخر يحافظ على حرارة الطعام طوال الجلسة بكل أناقة",
    heroAngle: "جلسة عائلية أدفأ مع طعام يحافظ على حرارته طوال الوقت",
    problemStatement: "الطعام يبرد خلال جلسات العائلة والضيوف الطويلة. سخّان المائدة يجعل كل وجبة مستعدة في أي وقت.",
    painSectionImage: "/images/products/smart-table-warmer-pain.png",
    painSectionImageAlt: "عائلة حول مائدة — الطعام بارد والمجهود يضيع",
    painSectionAspect: "822/1024",
    solutionSectionImage: "/images/products/smart-table-warmer-solution.png",
    solutionSectionImageAlt: "سخّان المائدة الذكي على مائدة — أطباق دافئة مع بخار",
    solutionSectionAspect: "1024/726",
    lifestyleSectionImage: "/images/products/smart-table-warmer-lifestyle.png",
    lifestyleSectionImageAlt: "سخّان المائدة الذكي في المطبخ — سهل التخزين والحمل",
    lifestyleSectionAspect: "819/1024",
    benefits: [
      "يحافظ على حرارة الطعام طوال الجلسة",
      "تصميم أنيق يناسب المائدة والضيافة",
      "آمن للاستخدام اليومي",
      "سهل التخزين والحمل",
      "مثالي للعائلة والضيوف",
    ],
    beforeLabel: "قبل: طعام بارد في منتصف الجلسة",
    beforeSectionImage: "/images/products/smart-table-warmer-before.png",
    beforeSectionImageAlt: "عائلة في المطبخ — إعادة تسخين الطعام في الميكروويف",
    beforeSectionAspect: "819/1024",
    afterLabel: "بعد متقن: طعام دافئ طوال الجلسة",
    afterSectionImage: "/images/products/smart-table-warmer-after.png",
    afterSectionImageAlt: "سخّان المائدة الذكي — أطباق دافئة مع بخار في المطبخ",
    afterSectionAspect: "819/1024",
    howToUse: [
      "ضع الطبق على السخّان",
      "اشغّل السخّان وانتظر لحظة",
      "استمتع بالطعام الدافئ طوال الجلسة",
    ],
    crossSellSlugs: ["pure-faucet-filter", "thermal-lunch-box"],
    reviews: [
      {
        name: "أم خالد",
        city: "الرياض",
        rating: 5,
        text: "مثالي للعزوم والعائلة. الطعام يبقى دافئ من بداية الجلسة للآخر. ممتاز ومريح جدًا.",
        photo: "/images/reviews/smart-table-warmer/review-unboxing.png",
        photoAlt: "صورة من أم خالد — السخّان بعد فتح الطرد",
        photoAspect: "1/1",
      },
      { name: "شيخة المري", city: "جدة", rating: 5, text: "أشكر متقن على هذا المنتج. جلساتنا العائلية صارت أجمل. الطعام يبقى كما هو." },
      {
        name: "مشاعل الدوسري",
        city: "الخبر",
        rating: 5,
        text: "العزايم صارت أحلى بكثير. الضيوف دائماً يسألون عنه.",
        photo: "/images/reviews/smart-table-warmer/review-in-use.png",
        photoAlt: "صورة من مشاعل — السخّان على المائدة",
        photoAspect: "400/300",
      },
      {
        name: "أم فيصل",
        city: "الرياض",
        rating: 5,
        text: "طلبت قطعتين وما ندمت. كل يوم نستخدمه في العشاء العائلي.",
        photo: "/images/reviews/smart-table-warmer/review-boxes.png",
        photoAlt: "صورة من أم فيصل — قطعتي السخّان بعد الاستلام",
        photoAspect: "443/590",
      },
      { name: "نورة الشثري", city: "القصيم", rating: 4, text: "تصميمه أنيق ويناسب السفرة. الطعام يبقى حار لفترة طويلة." },
      { name: "ريما الفهد", city: "المدينة", rating: 5, text: "هدية ممتازة لأي بيت سعودي. عملي وفخم ويستاهل كل ريال." },
    ],
    faqs: [
      { question: "هل يحافظ على حرارة الطعام؟", answer: "نعم، يعمل على الحفاظ على درجة الحرارة لفترات طويلة خلال الجلسة." },
      { question: "هل يناسب جلسات العائلة؟", answer: "نعم، صُمم خصيصًا للجلسات العائلية الطويلة والضيافة." },
      { question: "هل آمن للاستخدام؟", answer: "نعم، يعمل بمعايير السلامة المعتمدة. يُنصح بعدم ترك الأطفال الصغار دون مراقبة بالقرب منه." },
      { question: "كم مدة التوصيل؟", answer: "عادة 2-5 أيام عمل داخل المدن الرئيسية في المملكة." },
    ],
    seoTitle: "سخّان المائدة الذكي | متقن",
    seoDescription: "حل عملي فاخر يحافظ على حرارة الطعام طوال الجلسة. مثالي للعائلة والضيوف. اطلب الآن مع الدفع عند الاستلام.",
  },
  "thermal-lunch-box": {
    heroImageAlt: "حافظة الغداء الحرارية مع وجبة دافئة",
    shortPromise: "تجربة عملية تمنحك وجبات دافئة وجاهزة أينما كنت بسهولة وراحة",
    heroAngle: "وجبة دافئة معك أينما ذهبت في يومك",
    problemStatement: "الوجبة الباردة في العمل أو الدراسة تؤثر على يومك. الحافظة الحرارية تجعل وجبتك دافئة وجاهزة في أي وقت.",
    benefits: [
      "تحافظ على حرارة الوجبة لساعات",
      "خفيفة وسهلة الحمل",
      "مناسبة للعمل والدراسة والسفر",
      "سهلة التنظيف",
      "تصميم أنيق وعملي",
    ],
    beforeLabel: "قبل: وجبة باردة في العمل",
    afterLabel: "بعد متقن: وجبة دافئة أينما كنت",
    howToUse: [
      "ضع الوجبة الساخنة في الحافظة",
      "أغلقها جيدًا للحفاظ على الحرارة",
      "افتحها وقت الغداء واستمتع بوجبتك الدافئة",
    ],
    crossSellSlugs: ["smart-table-warmer", "powerful-cordless-vacuum"],
    reviews: [
      { name: "نادية الحمدان", city: "الدمام", rating: 5, text: "أفضل هدية أهديتها لنفسي. وجبتي تبقى دافئة من البيت للعمل. ممتازة وأنيقة." },
      { name: "رهف الصالح", city: "الرياض", rating: 4, text: "خفيفة ومريحة وتحافظ على الحرارة. أوصي فيها لكل من يأكل خارج البيت." },
      { name: "سمر الغامدي", city: "جدة", rating: 5, text: "زوجي يستخدمها يومياً للدوام. الأكل يوصل حار كأنه طازج." },
      { name: "لينا القحطاني", city: "الخبر", rating: 5, text: "أنيقة وعملية. الحجم مناسب ومريحة في الشنطة." },
      { name: "أمل الحارثي", city: "مكة", rating: 5, text: "أخذت وحدة لي ووحدة لبنتي في الجامعة. كلنا مبسوطات فيها." },
      { name: "روان المطيري", city: "تبوك", rating: 4, text: "تحافظ على الحرارة لساعات. جودة ممتازة والتوصيل كان سريع." },
    ],
    faqs: [
      { question: "هل تحافظ على الطعام دافئًا؟", answer: "نعم، تحافظ على الحرارة لعدة ساعات حسب الوجبة ودرجة الحرارة المحيطة." },
      { question: "هل تناسب الدوام والسفر؟", answer: "نعم، مناسبة للعمل والدراسة والسفر وأي يوم خارج البيت." },
      { question: "هل سهلة التنظيف؟", answer: "نعم، الداخل مصنوع من مواد سهلة التنظيف." },
      { question: "هل الدفع عند الاستلام؟", answer: "نعم، الدفع عند الاستلام متاح لجميع الطلبات." },
    ],
    seoTitle: "حافظة الغداء الحرارية | متقن",
    seoDescription: "تجربة عملية تمنحك وجبات دافئة أينما كنت. اطلب الآن من متقن مع الدفع عند الاستلام والتوصيل داخل السعودية.",
  },
};
